### ISSUE TITLE
Generate os:image from chart data

### ISSUE THREAD

**Issue by bvaughn** [bvaughn/planner#15]
It seems like Planner can generate plan-specific `og:image` images dynamically by rendering a Canvas on the server and then capturing a screenshot (using Puppeteer or Playwright) and returning that. Some related tweet threads:
* https://twitter.com/terrysahaidak/status/1478727805907214342
* https://twitter.com/MichaelDeBoey93/status/1478539507343441921
* https://twitter.com/anthonygarvan/status/1478512005275398148

Vercel's og-image repo might also be a nice starting point to fork:
https://github.com/vercel/og-image

This would be a nice upgrade from the current behavior which is to just return the following hard-coded `og:image`:

![Planner JS meta-image](https://user-images.githubusercontent.com/29597/148128667-3e2cd87a-3a7a-4123-bdbc-168965baa4e6.png)

**Comment by bvaughn** [comment]
Got a custom Next server setup to do this:
![image](https://user-images.githubusercontent.com/29597/148320942-9f082964-a4ea-4e84-9640-842eb00e0866.png)

Runs a little slow but seems to work:
https://user-images.githubusercontent.com/29597/148320962-4d4da03d-e249-4cd7-be2f-efba2ff855fc.mov

**Comment by bvaughn** [comment]
Here’s a good page to checkout for perf optimization ideas:
 https://twitter.com/codingbull/status/147894172075896012

**Comment by cliffordfajardo** [comment]
Another data point, Github engineering outlined how they generate their `og:image` for github repos (June 2021)
- https://github.blog/2021-06-22-framework-building-open-graph-images/

> _So: our custom Open Graph image service is a little Node.js app that uses the GitHub GraphQL API to collect data, generates some HTML from a template, and pipes it to Puppeteer to “take a screenshot” of that HTML. This is not a novel idea—lots of companies and projects (like vercel/og-image) use a similar process to generate an image._
