### ISSUE TITLE
Wrong Environment variables on production

### ISSUE THREAD

**Issue by tux-tn** [bvaughn/planner#20]
Looks like `ENV_HOST` and `NEXT_PUBLIC_VERCEL_URL` are set incorrectly for https://plannerjs.dev/  leading to mixed content warning for favicons and  invalid `og:url`.

Thank you for making this public btw. Awesome project :tada:

**Comment by bvaughn** [comment]
`ENV_HOST` is only used in DEV (local build - `.env.local`). In production the app falls back to using `NODE_ENV` to infer "http" or "https".

I'm not sure why the host is coming through as "http" though now b'c I've tried adding an environment variable on the Vercel side for production builds that specifies "https". Guess I'll need to look at it after work. Thanks for the heads up.

**Comment by bvaughn** [comment]
Oh, I think this is coming from the `_document.js` which can't access env variables. I need to add a fallback to look at the location. Lemme try something really quick.

**Comment by bvaughn** [comment]
Fixed via 7aa0fc0. Thanks again!
