### ISSUE TITLE
Planner should support color keywords, not just hex

### ISSUE THREAD

**Issue by rachelnabors** [bvaughn/planner#35]
# Example

Assigning a CSS color keyword like `black` instead of `#000000` to `color` throws error:

<img width="935" alt="Screen Shot 2022-02-03 at 1 21 20 PM" src="https://user-images.githubusercontent.com/236306/152351580-d20ff11f-db70-43ab-88d2-4b53d0f1fc8a.png">

# Expected Behavior

1. If `color`'s value doesn't begin with a `#`, compare it to a dictionary of CSS colors. 
2. If not in the dictionary, either throw error or use "transparent" (your choice).
3. If in the dictionary, use that keyword for the color.

**Comment by bvaughn** [comment]
Totally understand why this would be a nice  convenience feature- but it’s a hard limitation currently because of how my color highlighting (on hover) and contrast (foreground vs background color determination) works. I’d like to avoid having to hardcode a long list of CSS color names. (I think there are well over 100 of them?)

**Comment by rachelnabors** [comment]
>
> The browser itself could confirm whether or not the keyword is a valid
color like so:
https://stackoverflow.com/questions/48484767/javascript-check-if-string-is-valid-css-color

**Comment by bvaughn** [comment]
It’s not about confirmation- but rather, how to covert a color name to an rgb value (so I can calculate contrast).

**Comment by rachelnabors** [comment]
What about `getComputedStyle()`? 

https://stackoverflow.com/questions/1573053/javascript-function-to-convert-color-names-to-hex-codes/24390910

**Comment by bvaughn** [comment]
Oh, nice! That looks like it could work then as a fallback for non-hex colors.
