### ISSUE TITLE
Planner should have way to view very long timelines

### ISSUE THREAD

**Issue by rachelnabors** [bvaughn/planner#36]
# Example

When planning shorter duration efforts over longer time periods (think weeks in months), the bars get condensed to the point of not being legible at a glance:

<img width="1435" alt="Screen Shot 2022-02-03 at 1 39 39 PM" src="https://user-images.githubusercontent.com/236306/152353871-425a96d8-0c81-4f74-99c1-d6a45a8e7d90.png">

# Expected behavior

It would be useful to see a monthly or weekly view with a "map" of the greater whole to one side. 

Mural has a feature like this, as an example of what I'm describing:

<img width="1100" alt="Screen Shot 2022-02-03 at 1 44 39 PM" src="https://user-images.githubusercontent.com/236306/152354600-7581e4de-e7cc-4930-b732-c32bb3bd9170.png">

**Comment by bvaughn** [comment]
This issue is also related to #25 (zoom and pan support).

**Comment by bvaughn** [comment]
I’m on a train today with no wifi, so I can’t demo this yet- but I got horizontal pan and zoom working.

**Comment by bvaughn** [comment]
Fixed via #37
