### ISSUE TITLE
Render Timeline with Variable Timescales

### ISSUE THREAD

**Issue by peterdresslar** [bvaughn/planner#5]
Includes need for in-data length units, which I wish were named `duration`s. I'd be happy to take a hack at this. Should be able to support data inputs like:

```js
createTask({
  id: "mile",
  name: "Bar",
  month: 2,
  length: 3d,
  dependency: "m-dep",
  owner: "susan",
});
createTask({
  name: "Foo",
  month: 2,
  length: 1w,
  isOngoing: true,
  owner: "team",
});
createTask({
  name: "Baz",
  month: 2,
  length: 3m,
  isOngoing: true,
  owner: "team",
});
```

**Comment by bvaughn** [comment]
Hey hadn't gotten around to replying to this yet. Was still trying to decide if it was a feature I _wanted_ (to add/accept complexity for). My needs are pretty basic with Planner TBH>

**Comment by peterdresslar** [comment]
No worries! I just happen to have the same needs as the planner, but it's
your fun project. Sorry to push on features

**Comment by bvaughn** [comment]
No worries. Thanks for being so understanding 😄 

I'm open to looking at what you have in mind if you'd like to share a PR?

(Still planning to loop back to the other PR soon.)
