### ISSUE TITLE
Awsome little example!

### ISSUE THREAD

**Issue by pkellner** [bvaughn/planner#8]
Appreciate you making this public.  Good to see how you guys build React apps (from the view of the rest of us).  Took me a minute to realize that "loosing focus" updates the data when I type in changes.  No need (IMHO) to fix, but might be helpful to add a text note to that behavior.

**Comment by bvaughn** [comment]
> Took me a minute to realize that "loosing focus" updates the data when I type in changes.

That makes sense. It's less intuitive initially, but I think it's better for two reasons:
1. The undo/redo feature works better if it isn't literally saving every keystroke.
2. Mobile editing experience feels pretty broken if the Canvas is redrawing (and measuring) after every edit.

> might be helpful to add a text note to that behavior.

Any ideas on how to convey this?

**Comment by pkellner** [comment]
Without going crazy, maybe something simple like change the titles (Tasks changes to "Tasks (Mouse out to save changes)" when there are pending changes (same for right text window).  Again, this is totally cool as is.  No need to change.

**Comment by bvaughn** [comment]
Thanks for the feedback! Fixed in 63ea9f0:

https://user-images.githubusercontent.com/29597/147881444-2c7f4326-94e1-4471-b2a9-62674944421c.mov
